force-app/main/default/objects/Account/fields/Zentitle_Customer_ID__c.field-meta.xml
<CustomField>
    <fullName>Zentitle_Customer_ID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>This was created to store the customer id used in Zentitle.</description>
    <inlineHelpText>This is the customer ID number reference used by Zentitle for customer software licensing, this value should NOT be changed once set.</inlineHelpText>
    <label>Zentitle Customer ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Software_Entitlement__c/Software_Entitlement__c.object-meta.xml
<CustomObject>
    <description>This object holds the software entitlements that correspond to records in Zentitle for software license management.</description>
    <label>Software Entitlement</label>
    <nameField>
        <displayFormat>Entitlement-{0000000}</displayFormat>
        <label>Software Entitlement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Software Entitlements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Software_Entitlement__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>This holds the entitlement account, it should not be changed once set because there can be issues with the customer in Zentile not matching.</description>
    <inlineHelpText>This is the account the Entitlement is connected to. The account CANNOT be changed once the entitlement is created.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Software Entitlements</relationshipLabel>
    <relationshipName>Software_Entitlements</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Software_Entitlement__c/fields/Entitlement_Seat_Count__c.field-meta.xml
<CustomField>
    <fullName>Entitlement_Seat_Count__c</fullName>
    <description>This is the number of seats tied to the entitlement. This number is what would be changed to fire a change to Zentitle.</description>
    <inlineHelpText>This is the number of seats tied to the entitlement.</inlineHelpText>
    <label>Entitlement Seat Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Software_Entitlement__c/fields/Entitlement_Type__c.field-meta.xml
<CustomField>
    <fullName>Entitlement_Type__c</fullName>
    <description>This is used to support Entitlement bundles where multiple entitlements can be grouped to create an entitlement bundle stemming from a single offering. This is for future support.</description>
    <inlineHelpText>This is for future use with bundles. Currently, the option should be single to have a single entitlement.</inlineHelpText>
    <label>Entitlement Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Single</fullName>
            </value>
            <value>
                <fullName>Bundle</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Software_Entitlement__c/fields/Offering__c.field-meta.xml
<CustomField>
    <fullName>Offering__c</fullName>
    <description>This stores the SKU of the product for which the entitlement is offered. The SKU should not be changed once set.</description>
    <inlineHelpText>This is the SKU in zentile for the product being licensed. It should not be changed once set.</inlineHelpText>
    <label>SKU</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/UpsertRecordsActionTest.cls
/**
 * Description: This repo contains an Apex Invocable Action that provides the ability to Upsert Records in Lightning Flow from Salesforce.
 * https://github.com/ryanfollmer/UpsertRecordsFlowAction/blob/master/force-app/main/default/classes/UpsertRecordsActionTest.cls
 */

@IsTest
public class UpsertRecordsActionTest {
    
    @IsTest
    private static void testDefaultBehavior(){
        
// Create an Account to link with Software_Entitlement
        Account testAccount = new Account(
            Name = 'Test Account',
            Zentitle_Customer_ID__c = 'Test'
        );
        insert testAccount;
        
        
        List<UpsertRecordsAction.UpsertRequest> requests = new List<UpsertRecordsAction.UpsertRequest>();

        UpsertRecordsAction.UpsertRequest entmnts = new UpsertRecordsAction.UpsertRequest();

        List<Software_Entitlement__c> softwareEntitlements = new List<Software_Entitlement__c>();

        softwareEntitlements.add(new Software_Entitlement__c(
            Account__c = testAccount.Id,
            Entitlement_Type__c = 'Single',
            Offering__c = 'TEST',
            Entitlement_Seat_Count__c = 2
        ));
        softwareEntitlements.add(new Software_Entitlement__c(
            Account__c = testAccount.Id,
            Entitlement_Type__c = 'Single',
            Offering__c = 'TEST',
            Entitlement_Seat_Count__c = 2
        ));

        entmnts.records = softwareEntitlements;
        requests.add(entmnts);

        
// Create a Software Entitlement record linked to the newly created Account
        Software_Entitlement__c se = new Software_Entitlement__c(
            Account__c = testAccount.Id,
            Entitlement_Type__c = 'Single',
            Offering__c = 'TEST',
            Entitlement_Seat_Count__c = 2
        );
        
        
        
        List<UpsertRecordsAction.UpsertResult> results = UpsertRecordsAction.upsertRecords(requests);

        System.assert(results != null, 'Upsert Results should not be null.');
        System.assertEquals(2, results[0].results.size(), 'Result collection should contain 2 items.');
    }

    @IsTest
    private static void testUpsertUsingExternalIdKey(){
        
// Create an Account to link with Software_Entitlement
        Account testAccount = new Account(
            Name = 'Test Account',
            Zentitle_Customer_ID__c = 'Test'
        );
        insert testAccount;
        
     Software_Entitlement__c testSoftwareEntitlement = new Software_Entitlement__c(
            Account__c = testAccount.Id,
            Entitlement_Type__c = 'Single',
            Offering__c = 'TEST',
            Entitlement_Seat_Count__c = 2
        );


        List<UpsertRecordsAction.UpsertRequest> requests = new List<UpsertRecordsAction.UpsertRequest>();

        UpsertRecordsAction.UpsertRequest entmnts = new UpsertRecordsAction.UpsertRequest();

                
        List<Software_Entitlement__c> softwareEntitlements = new List<Software_Entitlement__c>();
		// Add existing single we already created
        softwareEntitlements.add(testSoftwareEntitlement);
        // Create new software entitlement to add
        softwareEntitlements.add(new Software_Entitlement__c(
            Account__c = testAccount.Id,
            Entitlement_Type__c = 'Single',
            Offering__c = 'TEST',
            Entitlement_Seat_Count__c = 2
        ));
        
        entmnts.records = softwareEntitlements;
        
        
        // Custom text field on Account object - flagged as External ID 
        entmnts.externalIDField = 'Zentitle_Attribute_ID__c';

        requests.add(entmnts);

        List<UpsertRecordsAction.UpsertResult> results = UpsertRecordsAction.upsertRecords(requests);

        System.assert(results != null, 'Upsert Results should not be null.');
        System.assertEquals(2, results[0].results.size(), 'Result collection should contain 2 items.');

    }
}